name: Autobump
on:
  schedule:
    # Runs daily at 8:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Git
        run: |
          # Use the GitHub Actions bot as the committer
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Formulae
        run: |
          brew tap ${{ github.repository }}
          brew test-bot --bump-only --tap=${{ github.repository }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
